
package pl.egu.agh.soa.lab;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service", targetNamespace = "http://lab.soa.agh.edu.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Service {


    /**
     * 
     * @param arg0
     * @return
     *     returns pl.egu.agh.soa.lab.GetStudentByNameResponse.Students
     */
    @WebMethod
    @WebResult(name = "students", targetNamespace = "")
    @RequestWrapper(localName = "getStudentByName", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.GetStudentByName")
    @ResponseWrapper(localName = "getStudentByNameResponse", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.GetStudentByNameResponse")
    public pl.egu.agh.soa.lab.GetStudentByNameResponse.Students getStudentByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param index
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteStudentByIndeX", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.DeleteStudentByIndeX")
    @ResponseWrapper(localName = "deleteStudentByIndeXResponse", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.DeleteStudentByIndeXResponse")
    public boolean deleteStudentByIndeX(
        @WebParam(name = "index", targetNamespace = "")
        int index);

    /**
     * 
     * @param arg0
     * @return
     *     returns pl.egu.agh.soa.lab.Student
     */
    @WebMethod
    @WebResult(name = "student", targetNamespace = "")
    @RequestWrapper(localName = "getStudentByIndex", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.GetStudentByIndex")
    @ResponseWrapper(localName = "getStudentByIndexResponse", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.GetStudentByIndexResponse")
    public Student getStudentByIndex(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param name
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteStudentByName", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.DeleteStudentByName")
    @ResponseWrapper(localName = "deleteStudentByNameResponse", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.DeleteStudentByNameResponse")
    public boolean deleteStudentByName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @return
     *     returns pl.egu.agh.soa.lab.GetStudentsResponse.Students
     */
    @WebMethod
    @WebResult(name = "students", targetNamespace = "")
    @RequestWrapper(localName = "getStudents", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.GetStudents")
    @ResponseWrapper(localName = "getStudentsResponse", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.GetStudentsResponse")
    public pl.egu.agh.soa.lab.GetStudentsResponse.Students getStudents();

    /**
     * 
     * @param name
     * @param index
     * @param age
     * @return
     *     returns pl.egu.agh.soa.lab.Student
     */
    @WebMethod
    @WebResult(name = "student", targetNamespace = "")
    @RequestWrapper(localName = "addNewStudent", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.AddNewStudent")
    @ResponseWrapper(localName = "addNewStudentResponse", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.AddNewStudentResponse")
    public Student addNewStudent(
        @WebParam(name = "index", targetNamespace = "")
        int index,
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "age", targetNamespace = "")
        int age);

    /**
     * 
     * @param arg0
     * @return
     *     returns pl.egu.agh.soa.lab.GetStudentByAgeResponse.Students
     */
    @WebMethod
    @WebResult(name = "students", targetNamespace = "")
    @RequestWrapper(localName = "getStudentByAge", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.GetStudentByAge")
    @ResponseWrapper(localName = "getStudentByAgeResponse", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.GetStudentByAgeResponse")
    public pl.egu.agh.soa.lab.GetStudentByAgeResponse.Students getStudentByAge(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param index
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBase64Avatar", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.GetBase64Avatar")
    @ResponseWrapper(localName = "getBase64AvatarResponse", targetNamespace = "http://lab.soa.agh.edu.pl/", className = "pl.egu.agh.soa.lab.GetBase64AvatarResponse")
    public String getBase64Avatar(
        @WebParam(name = "index", targetNamespace = "")
        int index);

}
